Fix migration results/0004 by creating initial migration for submissions
    $ docker-compose run web migrate
    Starting nextfilmfestby_data_1
    /app/lib/python2.7/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
      return meta(name, bases, d)

    /app/src/filmfest/urls.py:14: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got search.views.search). Pass the callable instead.
      url(r'^search/$', 'search.views.search', name='search'),  # noqa

    /app/src/filmfest/urls.py:15: RemovedInDjango110Warning: Calling i18n_patterns() with the `prefix` argument and with tuples instead of django.conf.urls.url() instances is deprecated and will no longer work in Django 1.10. Use a list of django.conf.urls.url() instances instead.
      url(r'', include(wagtail_urls)),

    /app/lib/python2.7/site-packages/django/conf/urls/i18n.py:25: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
      pattern_list = patterns(prefix, *args)

    Operations to perform:
      Apply all migrations: wagtailusers, wagtailembeds, wagtailadmin, sessions, admin, wagtailcore, results, auth, contenttypes, cpm_generic, taggit, wagtailsearch, home, wagtailforms, wagtailredirects, wagtailimages
    Running migrations:
      Rendering model states... DONE
      Applying contenttypes.0001_initial... OK
      Applying auth.0001_initial... OK
      Applying admin.0001_initial... OK
      Applying admin.0002_logentry_remove_auto_add... OK
      Applying contenttypes.0002_remove_content_type_name... OK
      Applying auth.0002_alter_permission_name_max_length... OK
      Applying auth.0003_alter_user_email_max_length... OK
      Applying auth.0004_alter_user_username_opts... OK
      Applying auth.0005_alter_user_last_login_null... OK
      Applying auth.0006_require_contenttypes_0002... OK
      Applying auth.0007_alter_validators_add_error_messages... OK
      Applying wagtailcore.0001_squashed_0016_change_page_url_path_to_text_field... OK
      Applying wagtailcore.0017_change_edit_page_permission_description... OK
      Applying wagtailcore.0018_pagerevision_submitted_for_moderation_index... OK
      Applying wagtailcore.0019_verbose_names_cleanup... OK
      Applying cpm_generic.0001_initial... OK
      Applying wagtailcore.0020_add_index_on_page_first_published_at... OK
      Applying wagtailcore.0021_capitalizeverbose... OK
      Applying wagtailcore.0022_add_site_name... OK
      Applying wagtailcore.0023_alter_page_revision_on_delete_behaviour... OK
      Applying wagtailcore.0024_collection... OK
      Applying wagtailcore.0025_collection_initial_data... OK
      Applying wagtailcore.0026_group_collection_permission... OK
      Applying wagtailcore.0027_fix_collection_path_collation... OK
      Applying wagtailcore.0024_alter_page_content_type_on_delete_behaviour... OK
      Applying wagtailcore.0028_merge... OK
      Applying home.0001_initial... OK
      Applying home.0002_create_homepage... OK
      Applying taggit.0001_initial... OK
      Applying taggit.0002_auto_20150616_2121... OK
      Applying wagtailimages.0001_initial... OK
      Applying wagtailimages.0002_initial_data... OK
      Applying wagtailimages.0003_fix_focal_point_fields... OK
      Applying wagtailimages.0004_make_focal_point_key_not_nullable... OK
      Applying wagtailimages.0005_make_filter_spec_unique... OK
      Applying wagtailimages.0006_add_verbose_names... OK
      Applying wagtailimages.0007_image_file_size... OK
      Applying wagtailimages.0008_image_created_at_index... OK
      Applying wagtailimages.0009_capitalizeverbose... OK
      Applying wagtailimages.0010_change_on_delete_behaviour... OK
      Applying results.0001_initial... OK
      Applying results.0002_resultspage_resultsrelatedjurymember... OK
      Applying results.0003_jurymemberpage_country... OK
      Applying results.0004_filmpage...Traceback (most recent call last):
      File "manage.py", line 21, in <module>
        main()
      File "manage.py", line 17, in main
        execute_from_command_line(sys.argv)
      File "/app/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
        utility.execute()
      File "/app/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/app/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/app/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
        output = self.handle(*args, **options)
      File "/app/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 200, in handle
        executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
      File "/app/lib/python2.7/site-packages/django/db/migrations/executor.py", line 92, in migrate
        self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
      File "/app/lib/python2.7/site-packages/django/db/migrations/executor.py", line 121, in _migrate_all_forwards
        state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
      File "/app/lib/python2.7/site-packages/django/db/migrations/executor.py", line 198, in apply_migration
        state = migration.apply(state, schema_editor)
      File "/app/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 90, in __exit__
        self.execute(sql)
      File "/app/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 110, in execute
        cursor.execute(sql, params)
      File "/app/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
        return super(CursorDebugWrapper, self).execute(sql, params)
      File "/app/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
        return self.cursor.execute(sql, params)
      File "/app/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
        six.reraise(dj_exc_type, dj_exc_value, traceback)
      File "/app/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
        return self.cursor.execute(sql, params)
    django.db.utils.ProgrammingError: relation "submissions_submission" does not exist