Install package postgresql in web container
This fixes the problem below after launching `docker-compose run web dbshell`:
```
CommandError: You appear not to have the 'psql' program installed or on
your path.
```

This also requires one to rebuild docker image with (restart of running
services isn't required):
```
docker-compose build web
```